id: P010552
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:38.243389
source_metadata:
  id: bdr:W1CZ1074
  title: འཇིགས་བྱེད་ཀྱི་བསྲུང་འཁོར་གི་ཕྱག་ལེན་བཀའ་རྒྱ་མ
  author: ''
  volumes:
    c0af3a0e4f374fefb01545a04dfe68d2:
      image_group_id: I1CZ1439
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
